# appveyor.bat
# Copyright (c) 2018-2019 Pablo Acosta-Serafini
# See LICENSE for details
# yamllint disable rule:document-start
# yamllint disable rule:line-length

environment:
  matrix:
    - JOB: "2.7"
      INTERP: "py27"
      PYVER: "2.7"
    - JOB: "3.5"
      INTERP: "py35"
      PYVER: "3.5"
    - JOB: "3.6"
      INTERP: "py36"
      PYVER: "3.6"
    - JOB: "3.7"
      INTERP: "py37"
      PYVER: "3.7"

init:
  - echo "PYVER=%PYVER%"

install:
  ###
  # Set up environment variables
  ###
  - SET
  - python --version
  - SET REPO_DIR=%CD%
  - SET RESULTS_DIR=%REPO_DIR%\results
  ###
  # Install shellcheck and bash binaries
  ###
  - CD %REPO_DIR%
  - curl --output shellcheck-stable.zip https://storage.googleapis.com/shellcheck/shellcheck-stable.zip
  - 7z -y e shellcheck-stable.zip
  - MOVE shellcheck-stable.exe shellcheck.exe
  - SET PATH=%REPO_DIR%;%PATH%
  ###
  # Create directories for reports and artifacts
  ###
  - IF NOT EXIST "%RESULTS_DIR%\artifacts" mkdir %RESULTS_DIR%\artifacts

build_script:
  - python -m pip install -r%REPO_DIR%\data\requirements.txt

test_script:
  - CD %REPO_DIR%
  - SET PYTHONPATH=%CD%/sphinxcontrib;%PYTHONPATH%
  - pytest -s -x -vv tests\test_sphinxcontrib.py

on_failure:
  - 7z a %RESULTS_DIR%\artifacts_%INTERP%.zip %RESULTS_DIR%\artifacts\*.*
  - appveyor PushArtifact %RESULTS_DIR%\artifacts_%INTERP%.zip
